import Head from 'next/head'
import { useState } from 'react'
import axios from 'axios';
import dayjs from 'dayjs';

export default function Home() {
  const today = dayjs().format("YYYY-MM-DD");
  const [loading, setLoading] = useState(false);;
  const [dateSelected, setDateSelected] = useState(today);
  const [customerBalance, setCustomerBalance] = useState({});

  const accountNumber = '60241708';

  const url = `https://localhost:7217/api/v1/Account/${accountNumber}/balance`;


  const handleChange = (e) => {
    setDateSelected(e.target.value)
  }

  const handleClick = async (e) => {
    e.preventDefault();
    setLoading(true);
    const response = await axios.get(`${url}/?date=${dateSelected}`);
    setCustomerBalance(response.data.data);
    console.log("API response", response)
    setLoading(false);
  }

  const pageContent = loading ? <div>Loading...</div> : (
    <div>
      <br />
      <div>Balance: ${customerBalance.balance ? (customerBalance.balance).toFixed(2) : 0}</div>
      <br />
      <div>Total Credits: ${customerBalance.totalCredits ? (customerBalance.totalCredits).toFixed(2) : 0}</div>
      <br />
      <div>Total Debits: ${customerBalance.totalDebits ? (customerBalance.totalDebits).toFixed(2) : 0}</div>
    </div>
  );
  return (
    <>
      <Head>
        <title>DIDFrontend</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='grid h-full pt-6 place-items-center w-100'>
        <h1 className='text-xl sm:text-4xl underline mb-8'>Welcome to your Dashboard</h1>
        <h3 className='px-2 mb-3'>Please select a date to calculate balances for account number: <b>{accountNumber}</b></h3>
        <form>
          <label className='mr-6' htmlFor='date'>Select a date</label>
          <input className='border-2 p-1 rounded-md' type='date' name='date' id='date' value={dateSelected} onChange={handleChange} />
        </form>
        {pageContent}
        <button onClick={handleClick} className='text-sm mt-3 rounded-lg px-3 py-1 bg-teal-700 text-white font-medium'>Get EoD Balance</button>
      </main>
    </>
  )
}
